"""
Generate Figure 9, Figure S9, and Figure S10 directly from completed run outputs.

This script does not contain manually entered performance, stability, recurrence,
or LOCO values. All plotted numerical data are read from CSV files generated by:
  - repeated_10x5_k20_lr_V2.py
  - full_transfer_safe_loco_GENELEVEL_V2.py
  - the main NIBFS notebook (frozen top-20 panel)

Recommended Colab use:
    %run -i "/path/to/plot_Figure9_S9_S10_from_run_outputs.py"

Optional before running:
    PUBLICATION_PROJECT_DIR = "/content/.../NIBFS_REVIEWER_STYLE_FINAL_K20_COMPLETE"
"""

from __future__ import annotations

from pathlib import Path
import hashlib
import json
import os
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =============================================================================
# 0. Locate project and source files
# =============================================================================

def _find_project_dir() -> Path:
    """Find the single project root without assuming a fixed Drive mount name."""
    override = (
        globals().get("PUBLICATION_PROJECT_DIR", None)
        or globals().get("PROJECT_DIR", None)
        or os.environ.get("PUBLICATION_PROJECT_DIR")
    )
    if override:
        p = Path(str(override)).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"PUBLICATION_PROJECT_DIR tidak ditemukan: {p}")
        return p

    cwd = Path.cwd().resolve()
    if (cwd / "results" / "REPEATED_10X5_K20_LR").is_dir():
        return cwd

    candidates: list[Path] = []
    for script in Path("/content").glob(
        "gdrive*/MyDrive/**/src/repeated_10x5_k20_lr_V2.py"
    ):
        root = script.parents[1]
        if (root / "results" / "REPEATED_10X5_K20_LR").is_dir():
            candidates.append(root.resolve())

    # Broader fallback, still requiring the completed repeated-output directory.
    if not candidates:
        for rep_dir in Path("/content").glob(
            "gdrive*/MyDrive/**/results/REPEATED_10X5_K20_LR"
        ):
            candidates.append(rep_dir.parents[1].resolve())

    unique = sorted(set(candidates), key=lambda p: str(p))
    if len(unique) == 1:
        return unique[0]
    if not unique:
        raise FileNotFoundError(
            "Project tidak ditemukan. Set variabel PUBLICATION_PROJECT_DIR "
            "ke root project sebelum menjalankan script."
        )
    raise RuntimeError(
        "Ditemukan lebih dari satu kandidat project. Set PUBLICATION_PROJECT_DIR.\n"
        + "\n".join(str(p) for p in unique)
    )


def _latest_matching_file(root: Path, patterns: list[str]) -> Path:
    matches: list[Path] = []
    for pattern in patterns:
        matches.extend(p for p in root.rglob(pattern) if p.is_file())
    if not matches:
        raise FileNotFoundError(
            "Tidak ditemukan file untuk pola:\n  - " + "\n  - ".join(patterns)
        )
    return max(matches, key=lambda p: p.stat().st_mtime)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


PROJECT_DIR = _find_project_dir()
REPEATED_DIR = PROJECT_DIR / "results" / "REPEATED_10X5_K20_LR"
LOCO_DIR = PROJECT_DIR / "results" / "LOCO_FULL_TRANSFER_SAFE_GENELEVEL_V2"
OUTPUT_DIR = PROJECT_DIR / "results" / "PUBLICATION_FIGURES_FROM_RUN_OUTPUTS"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SOURCE_FILES = {
    "repeated_oof_summary": REPEATED_DIR / "repeated_oof_performance_summary.csv",
    "repeated_stability_summary": REPEATED_DIR / "repeated_stability_summary.csv",
    "repeated_gene_frequency": REPEATED_DIR / "repeated_gene_selection_frequency.csv",
    "loco_metrics": LOCO_DIR / "loco_metrics_genelevel.csv",
    "loco_summary": LOCO_DIR / "loco_primary_eligible_summary_genelevel.csv",
    "loco_gene_frequency": LOCO_DIR / "loco_gene_selection_frequency_genelevel.csv",
}

for label, path in SOURCE_FILES.items():
    if not path.is_file():
        raise FileNotFoundError(f"File sumber {label} tidak ditemukan: {path}")

# Frozen panel comes from the main notebook run, never from repeated or LOCO.
def _find_frozen_panel(root: Path) -> Path:
    matches = list(root.rglob("final_NIBFS_gene_panel_k20.csv"))
    matches += list(root.rglob("final_top20_NIBFS_gene_panel.csv"))
    matches = [p for p in matches if p.is_file()]
    if not matches:
        raise FileNotFoundError(
            "Frozen top-20 panel tidak ditemukan. Dicari: "
            "final_NIBFS_gene_panel_k20.csv"
        )
    preferred = [
        p for p in matches
        if "runs" in p.parts
        and "results" in p.parts
        and "tables" in p.parts
    ]
    pool = preferred if preferred else matches
    return max(pool, key=lambda p: p.stat().st_mtime)


FROZEN_PANEL_FILE = _find_frozen_panel(PROJECT_DIR)
SOURCE_FILES["frozen_top20_panel"] = FROZEN_PANEL_FILE

print("PROJECT_DIR       :", PROJECT_DIR)
print("REPEATED_DIR      :", REPEATED_DIR)
print("LOCO_DIR          :", LOCO_DIR)
print("FROZEN_PANEL_FILE :", FROZEN_PANEL_FILE)
print("OUTPUT_DIR        :", OUTPUT_DIR)


# =============================================================================
# 1. Load only CSV outputs generated by the completed analyses
# =============================================================================
r_perf = pd.read_csv(SOURCE_FILES["repeated_oof_summary"])
r_stab = pd.read_csv(SOURCE_FILES["repeated_stability_summary"])
r_genes_all = pd.read_csv(SOURCE_FILES["repeated_gene_frequency"])

l_metrics = pd.read_csv(SOURCE_FILES["loco_metrics"])
l_summary = pd.read_csv(SOURCE_FILES["loco_summary"])
l_genes = pd.read_csv(SOURCE_FILES["loco_gene_frequency"])

frozen_panel = pd.read_csv(FROZEN_PANEL_FILE)

required_columns = {
    "repeated_oof_summary": {
        "Method", "ROC_AUC_count", "ROC_AUC_mean", "ROC_AUC_std"
    },
    "repeated_stability_summary": {
        "Method", "Repeats", "Mean_of_repeat_mean_Jaccard",
        "SD_of_repeat_mean_Jaccard"
    },
    "repeated_gene_frequency": {
        "Method", "Gene", "Selection_frequency", "Total_fold_panels",
        "Selection_proportion", "Mean_selection_rank"
    },
    "loco_metrics": {
        "Held_out_cohort", "Model", "Normal", "Cancer", "Total",
        "Primary_ROC_AUC_eligible"
    },
    "loco_summary": {
        "Model", "Eligible_cohorts", "Mean_ROC_AUC", "SD_ROC_AUC"
    },
    "loco_gene_frequency": {
        "Gene", "Selection_frequency", "Selection_proportion",
        "Mean_panel_position"
    },
    "frozen_top20_panel": {"Gene"},
}

loaded_frames = {
    "repeated_oof_summary": r_perf,
    "repeated_stability_summary": r_stab,
    "repeated_gene_frequency": r_genes_all,
    "loco_metrics": l_metrics,
    "loco_summary": l_summary,
    "loco_gene_frequency": l_genes,
    "frozen_top20_panel": frozen_panel,
}

for label, required in required_columns.items():
    missing = required - set(loaded_frames[label].columns)
    if missing:
        raise ValueError(f"Kolom hilang pada {label}: {sorted(missing)}")


# =============================================================================
# 2. Integrity checks: stop rather than plot partial/inconsistent outputs
# =============================================================================
EXPECTED_METHODS = ["NIBFS", "DEG-only", "mRMR", "LASSO"]
EXPECTED_MODELS = ["LR", "RF", "LightGBM"]

missing_methods = set(EXPECTED_METHODS) - set(r_perf["Method"])
missing_methods |= set(EXPECTED_METHODS) - set(r_stab["Method"])
if missing_methods:
    raise RuntimeError(f"Metode repeated belum lengkap: {sorted(missing_methods)}")

perf_check = r_perf.set_index("Method").loc[EXPECTED_METHODS]
stab_check = r_stab.set_index("Method").loc[EXPECTED_METHODS]

if not (pd.to_numeric(perf_check["ROC_AUC_count"]) == 10).all():
    raise RuntimeError(
        "Repeated OOF belum lengkap: ROC_AUC_count harus 10 untuk semua metode."
    )
if not (pd.to_numeric(stab_check["Repeats"]) == 10).all():
    raise RuntimeError(
        "Repeated stability belum lengkap: Repeats harus 10 untuk semua metode."
    )

r_genes = r_genes_all.loc[r_genes_all["Method"] == "NIBFS"].copy()
if r_genes.empty:
    raise RuntimeError("Baris NIBFS tidak ditemukan pada repeated gene frequency.")
if set(pd.to_numeric(r_genes["Total_fold_panels"]).dropna().astype(int)) != {50}:
    raise RuntimeError(
        "Repeated gene recurrence belum lengkap: Total_fold_panels harus 50."
    )

missing_models = set(EXPECTED_MODELS) - set(l_summary["Model"])
if missing_models:
    raise RuntimeError(f"Model LOCO belum lengkap: {sorted(missing_models)}")

cohort_columns = [
    "Held_out_cohort", "Normal", "Cancer", "Total",
    "Primary_ROC_AUC_eligible"
]
cohorts = (
    l_metrics[cohort_columns]
    .drop_duplicates()
    .sort_values("Held_out_cohort")
    .reset_index(drop=True)
)
if cohorts["Held_out_cohort"].nunique() != len(cohorts):
    raise RuntimeError("Komposisi cohort LOCO tidak konsisten antar-model.")

eligible_from_metrics = int(cohorts["Primary_ROC_AUC_eligible"].astype(bool).sum())
eligible_from_summary = set(
    pd.to_numeric(l_summary["Eligible_cohorts"]).dropna().astype(int)
)
if eligible_from_summary != {eligible_from_metrics}:
    raise RuntimeError(
        "Jumlah cohort eligible pada LOCO summary tidak cocok dengan LOCO metrics: "
        f"summary={sorted(eligible_from_summary)}, metrics={eligible_from_metrics}."
    )

# Use the actual frozen-panel rank if available; otherwise preserve CSV row order.
if "Rank_NIBFS" in frozen_panel.columns:
    frozen_panel = frozen_panel.sort_values("Rank_NIBFS")
frozen_genes = frozen_panel["Gene"].astype(str).drop_duplicates().tolist()
if len(frozen_genes) != 20:
    raise RuntimeError(
        f"Frozen panel harus berisi 20 gen unik, ditemukan {len(frozen_genes)}."
    )

print("\nINTEGRITY CHECK PASSED")
print("Repeated repeats       :", int(stab_check["Repeats"].min()))
print("Repeated fold panels   :", int(r_genes["Total_fold_panels"].iloc[0]))
print("LOCO held-out cohorts  :", len(cohorts))
print("LOCO eligible cohorts  :", eligible_from_metrics)
print("Frozen genes           :", len(frozen_genes))


# =============================================================================
# 3. Prepare plotting tables without manually entering numerical results
# =============================================================================
method_order = EXPECTED_METHODS
model_order = EXPECTED_MODELS

st = r_stab.set_index("Method").loc[method_order].copy()
pe = r_perf.set_index("Method").loc[method_order].copy()
ls = l_summary.set_index("Model").loc[model_order].copy()

rep_recurrence = r_genes[["Gene", "Selection_proportion"]].rename(
    columns={"Selection_proportion": "Repeated_50fold_proportion"}
)
loco_recurrence = l_genes[["Gene", "Selection_proportion"]].rename(
    columns={"Selection_proportion": "LOCO_11panel_proportion"}
)
recurrence = (
    pd.DataFrame({"Gene": frozen_genes, "Frozen_rank": range(1, 21)})
    .merge(rep_recurrence, on="Gene", how="left")
    .merge(loco_recurrence, on="Gene", how="left")
    .fillna({
        "Repeated_50fold_proportion": 0.0,
        "LOCO_11panel_proportion": 0.0,
    })
    .sort_values("Frozen_rank")
)

# Save exact plotting data so every point/bar can be audited.
st.reset_index().to_csv(OUTPUT_DIR / "Figure9_S9_source_repeated_stability.csv", index=False)
pe.reset_index().to_csv(OUTPUT_DIR / "Figure9_S9_source_repeated_oof.csv", index=False)
ls.reset_index().to_csv(OUTPUT_DIR / "Figure9_S10_source_loco_summary.csv", index=False)
cohorts.to_csv(OUTPUT_DIR / "FigureS10_source_loco_cohorts.csv", index=False)
r_genes.to_csv(OUTPUT_DIR / "FigureS9_source_repeated_NIBFS_genes.csv", index=False)
l_genes.to_csv(OUTPUT_DIR / "FigureS10_source_loco_genes.csv", index=False)
recurrence.to_csv(OUTPUT_DIR / "Figure9_source_frozen_panel_recurrence.csv", index=False)


# =============================================================================
# 4. Styling only; no numerical results are stored below
# =============================================================================
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 9,
    "axes.titlesize": 10.5,
    "axes.labelsize": 9,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})

COLORS = {
    "NIBFS": "#0072B2",
    "DEG-only": "#D55E00",
    "mRMR": "#009E73",
    "LASSO": "#CC79A7",
    "LR": "#0072B2",
    "RF": "#D55E00",
    "LightGBM": "#009E73",
    "Repeated": "#0072B2",
    "LOCO": "#E69F00",
    "Normal": "#56B4E9",
    "Cancer": "#D55E00",
}


def _save_both(fig: plt.Figure, stem: str) -> None:
    fig.savefig(OUTPUT_DIR / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(OUTPUT_DIR / f"{stem}.png", dpi=600, bbox_inches="tight")


# =============================================================================
# 5. Figure 9: combined repeated and LOCO robustness
# =============================================================================
fig = plt.figure(figsize=(11.2, 8.2), constrained_layout=True)
gs = fig.add_gridspec(2, 2, height_ratios=[1.0, 1.25])

# A. Repeated stability
ax = fig.add_subplot(gs[0, 0])
x = np.arange(len(method_order))
ax.bar(
    x,
    st["Mean_of_repeat_mean_Jaccard"],
    yerr=st["SD_of_repeat_mean_Jaccard"],
    capsize=4,
    color=[COLORS[m] for m in method_order],
    edgecolor="black",
    linewidth=0.6,
)
ax.set_xticks(x, method_order)
ax.set_ylim(0, 1.02)
ax.set_ylabel("Mean within-repeat Jaccard")
ax.set_title("A  Repeated 10×5-fold selection stability", loc="left", fontweight="bold")
ax.grid(axis="y", alpha=0.25)
for i, value in enumerate(st["Mean_of_repeat_mean_Jaccard"]):
    ax.text(i, value + 0.045, f"{value:.3f}", ha="center", va="bottom", fontsize=8)

# B. Repeated OOF ROC-AUC
ax = fig.add_subplot(gs[0, 1])
ax.bar(
    x,
    pe["ROC_AUC_mean"],
    yerr=pe["ROC_AUC_std"],
    capsize=4,
    color=[COLORS[m] for m in method_order],
    edgecolor="black",
    linewidth=0.6,
)
auc_min = max(0.0, float(pe["ROC_AUC_mean"].min() - 0.010))
ax.set_xticks(x, method_order)
ax.set_ylim(auc_min, 1.001)
ax.set_ylabel("OOF ROC-AUC")
ax.set_title("B  Repeated OOF discrimination (LR)", loc="left", fontweight="bold")
ax.grid(axis="y", alpha=0.25)
for i, value in enumerate(pe["ROC_AUC_mean"]):
    ax.text(i, value + 0.0008, f"{value:.4f}", ha="center", va="bottom", fontsize=8)

# C. Transfer-safe LOCO summary
ax = fig.add_subplot(gs[1, 0])
x2 = np.arange(len(model_order))
ax.bar(
    x2,
    ls["Mean_ROC_AUC"],
    yerr=ls["SD_ROC_AUC"],
    capsize=4,
    color=[COLORS[m] for m in model_order],
    edgecolor="black",
    linewidth=0.6,
)
loco_ymin = max(0.0, float(ls["Mean_ROC_AUC"].min() - ls["SD_ROC_AUC"].max() - 0.06))
ax.set_xticks(x2, model_order)
ax.set_ylim(loco_ymin, 1.01)
ax.set_ylabel("Mean LOCO ROC-AUC")
ax.set_title(
    f"C  Transfer-safe LOCO across {eligible_from_metrics} eligible cohorts",
    loc="left",
    fontweight="bold",
)
ax.grid(axis="y", alpha=0.25)
for i, value in enumerate(ls["Mean_ROC_AUC"]):
    ax.text(i, value + 0.012, f"{value:.3f}", ha="center", va="bottom", fontsize=8)

# D. Frozen-panel recurrence under repeated and LOCO perturbations
ax = fig.add_subplot(gs[1, 1])
plot_rec = recurrence.sort_values("Frozen_rank", ascending=False).reset_index(drop=True)
y = np.arange(len(plot_rec))
h = 0.36
ax.barh(
    y - h / 2,
    plot_rec["Repeated_50fold_proportion"],
    height=h,
    color=COLORS["Repeated"],
    label="Repeated 50 folds",
)
ax.barh(
    y + h / 2,
    plot_rec["LOCO_11panel_proportion"],
    height=h,
    color=COLORS["LOCO"],
    label=f"LOCO {len(cohorts)} panels",
)
ax.set_yticks(y, plot_rec["Gene"])
ax.set_xlim(0, 1.05)
ax.set_xlabel("Selection proportion")
ax.set_title("D  Frozen-panel recurrence under two perturbations", loc="left", fontweight="bold")
ax.grid(axis="x", alpha=0.25)
ax.legend(frameon=False, fontsize=7.5, loc="lower right")

fig.suptitle(
    "Repeated-resampling and cross-cohort robustness of NIBFS",
    fontsize=13,
    fontweight="bold",
)
_save_both(fig, "Figure_9_Repeated_and_LOCO_robustness")
plt.close(fig)


# =============================================================================
# 6. Figure S9: detailed repeated 10×5 analysis
# =============================================================================
fig, axes = plt.subplots(1, 3, figsize=(12.0, 4.2), constrained_layout=True)

ax = axes[0]
ax.bar(
    x,
    st["Mean_of_repeat_mean_Jaccard"],
    yerr=st["SD_of_repeat_mean_Jaccard"],
    capsize=4,
    color=[COLORS[m] for m in method_order],
    edgecolor="black",
    linewidth=0.6,
)
ax.set_xticks(x, method_order, rotation=20)
ax.set_ylim(0, 1.02)
ax.set_ylabel("Mean within-repeat Jaccard")
ax.set_title("A  Stability", loc="left", fontweight="bold")
ax.grid(axis="y", alpha=0.25)

ax = axes[1]
ax.bar(
    x,
    pe["ROC_AUC_mean"],
    yerr=pe["ROC_AUC_std"],
    capsize=4,
    color=[COLORS[m] for m in method_order],
    edgecolor="black",
    linewidth=0.6,
)
ax.set_xticks(x, method_order, rotation=20)
ax.set_ylim(auc_min, 1.001)
ax.set_ylabel("OOF ROC-AUC")
ax.set_title("B  Repeated OOF performance", loc="left", fontweight="bold")
ax.grid(axis="y", alpha=0.25)

ax = axes[2]
rg = (
    r_genes.sort_values(
        ["Selection_frequency", "Mean_selection_rank", "Gene"],
        ascending=[False, True, True],
    )
    .head(20)
    .sort_values(
        ["Selection_frequency", "Mean_selection_rank", "Gene"],
        ascending=[True, False, False],
    )
)
y = np.arange(len(rg))
ax.barh(y, rg["Selection_proportion"], color=COLORS["Repeated"])
ax.set_yticks(y, rg["Gene"])
ax.set_xlim(0, 1.05)
ax.set_xlabel("Selection proportion")
ax.set_title("C  Most recurrent NIBFS genes", loc="left", fontweight="bold")
ax.grid(axis="x", alpha=0.25)

_save_both(fig, "Figure_S9_Repeated_10x5_robustness")
plt.close(fig)


# =============================================================================
# 7. Figure S10: detailed transfer-safe LOCO analysis
# =============================================================================
fig, axes = plt.subplots(1, 3, figsize=(12.0, 4.4), constrained_layout=True)

ax = axes[0]
y = np.arange(len(cohorts))
ax.barh(y, cohorts["Normal"], label="Normal", color=COLORS["Normal"])
ax.barh(
    y,
    cohorts["Cancer"],
    left=cohorts["Normal"],
    label="Cancer",
    color=COLORS["Cancer"],
)
ax.set_yticks(y, cohorts["Held_out_cohort"])
ax.invert_yaxis()
ax.set_xlabel("Held-out samples")
ax.set_title("A  LOCO cohort composition", loc="left", fontweight="bold")
ax.legend(frameon=False, fontsize=7, loc="lower right")
for yi, row in cohorts.iterrows():
    if bool(row["Primary_ROC_AUC_eligible"]):
        ax.text(float(row["Total"]) + 2, yi, "eligible", va="center", fontsize=7)

ax = axes[1]
ax.bar(
    x2,
    ls["Mean_ROC_AUC"],
    yerr=ls["SD_ROC_AUC"],
    capsize=4,
    color=[COLORS[m] for m in model_order],
    edgecolor="black",
    linewidth=0.6,
)
ax.set_xticks(x2, model_order)
ax.set_ylim(loco_ymin, 1.01)
ax.set_ylabel("ROC-AUC")
ax.set_title("B  Eligible-cohort mean ± SD", loc="left", fontweight="bold")
ax.grid(axis="y", alpha=0.25)

ax = axes[2]
lg = (
    l_genes.sort_values(
        ["Selection_frequency", "Mean_panel_position", "Gene"],
        ascending=[False, True, True],
    )
    .head(20)
    .sort_values(
        ["Selection_frequency", "Mean_panel_position", "Gene"],
        ascending=[True, False, False],
    )
)
y = np.arange(len(lg))
ax.barh(y, lg["Selection_proportion"], color=COLORS["LOCO"])
ax.set_yticks(y, lg["Gene"])
ax.set_xlim(0, 1.05)
ax.set_xlabel("Selection proportion")
ax.set_title("C  Most recurrent LOCO genes", loc="left", fontweight="bold")
ax.grid(axis="x", alpha=0.25)

_save_both(fig, "Figure_S10_Transfer_safe_LOCO")
plt.close(fig)


# =============================================================================
# 8. Provenance manifest for audit
# =============================================================================
manifest_rows = []
for label, path in SOURCE_FILES.items():
    manifest_rows.append({
        "Source_label": label,
        "Source_path": str(path),
        "SHA256": _sha256(path),
        "Size_bytes": path.stat().st_size,
        "Modified_time": path.stat().st_mtime,
    })

manifest = pd.DataFrame(manifest_rows)
manifest.to_csv(OUTPUT_DIR / "FIGURE_9_S9_S10_SOURCE_MANIFEST.csv", index=False)

run_record = {
    "project_dir": str(PROJECT_DIR),
    "output_dir": str(OUTPUT_DIR),
    "figures": [
        "Figure_9_Repeated_and_LOCO_robustness",
        "Figure_S9_Repeated_10x5_robustness",
        "Figure_S10_Transfer_safe_LOCO",
    ],
    "data_policy": (
        "All plotted numerical values were read from completed run-output CSVs. "
        "No performance, stability, gene-frequency, or LOCO values were manually entered."
    ),
    "repeated_repeats": int(stab_check["Repeats"].min()),
    "repeated_fold_panels": int(r_genes["Total_fold_panels"].iloc[0]),
    "loco_cohorts": int(len(cohorts)),
    "loco_eligible_cohorts": int(eligible_from_metrics),
    "frozen_panel_size": int(len(frozen_genes)),
}
(OUTPUT_DIR / "FIGURE_9_S9_S10_RUN_RECORD.json").write_text(
    json.dumps(run_record, indent=2), encoding="utf-8"
)

print("\nSELESAI. File yang dibuat:")
for path in sorted(OUTPUT_DIR.iterdir()):
    print(" -", path.name)
